---
- name: generate {{locale}}
  command: /usr/sbin/locale-gen {{locale}}
  tags: locale
- name: set locale to {{locale}}
  command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
  tags: locale
- name: set /etc/localtime to {{timezone}}
  command: /bin/cp /usr/share/zoneinfo/{{timezone}} /etc/localtime
- name: set /etc/timezone to {{timezone}}
  template: src=timezone dest=/etc/timezone
  notify: update tzdata
  tags: locale

- name: install logrotate
  apt: name=logrotate update-cache=yes

- name: package deps
  apt: name=python-pycurl

- name: install git
  apt: name=git

- name: install etckeeper
  apt: name=etckeeper

- name: dont use bzr for etckeeper
  lineinfile: dest=/etc/etckeeper/etckeeper.conf regexp="^VCS=\"(?!git)" state=absent

- name: use git for etckeeper
  lineinfile: dest=/etc/etckeeper/etckeeper.conf regexp="^VCS=\"git\"" insertbefore=BOF line="VCS=\"git\""

- name: initialize repo
  command: etckeeper init creates=/etc/.git

- name: initial commit
  command: etckeeper commit "Ansible commit"
  ignore_errors: yes

